//! The credentials a client presents to its home relay.
//!
//! Authorizing a connection takes two secrets that the app hands to the game DLL
//! at launch: the coordinator-signed authorization [`SignedToken`], and the
//! Ed25519 private key whose public half the token embeds. The token says *which*
//! slot in *which* session this client may submit turns for; the private key
//! proves the presenter is the client the token was minted for, by signing the
//! relay's connection-binding challenge. An [`Identity`] bundles the two so a
//! single value carries everything one connection needs.
//!
//! The private key is per-session and ephemeral — generated by the app, never
//! persisted, and living only inside trusted local processes — so it stays out of
//! this type's public surface: an `Identity` can sign a challenge but never hands
//! the key material back out.

use ring::signature::Ed25519KeyPair;

use rally_point_proto::token::SignedToken;

/// A client's per-session connection credentials: its signed authorization token
/// and the Ed25519 signing key that proves possession of the public key the token
/// commits to.
pub struct Identity {
    pub(crate) token: SignedToken,
    pub(crate) signing_key: Ed25519KeyPair,
}

/// Why a client's signing key could not be loaded.
#[derive(Debug, thiserror::Error)]
pub enum IdentityError {
    /// The supplied bytes are not a valid PKCS#8-encoded Ed25519 private key.
    #[error("client signing key is not a valid PKCS#8 Ed25519 key: {0}")]
    Key(String),
}

impl Identity {
    /// Builds an identity from a signed token and the client's Ed25519 private key
    /// in PKCS#8 v2 form — the document `ring`'s `generate_pkcs8` produces, which
    /// the app generates and passes down at launch.
    ///
    /// This does not check that the key matches the public key embedded in the
    /// token; a mismatch is caught by the relay when it rejects the challenge
    /// response, which is exactly where the authority to make that call lives.
    pub fn from_pkcs8(token: SignedToken, pkcs8: &[u8]) -> Result<Self, IdentityError> {
        let signing_key =
            Ed25519KeyPair::from_pkcs8(pkcs8).map_err(|err| IdentityError::Key(err.to_string()))?;
        Ok(Self { token, signing_key })
    }

    /// The authorization token this identity presents.
    pub fn token(&self) -> &SignedToken {
        &self.token
    }
}
